//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2084_a2_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public int Id { get; set; }
        public string authorId { get; set; }
        public string callSign { get; set; }
        public string brand { get; set; }
        public Nullable<int> year { get; set; }
        public string model { get; set; }
        public string vin { get; set; }
        public Nullable<int> hours { get; set; }
        public string odometerUnit { get; set; }
        public Nullable<int> odometer { get; set; }
        public Nullable<System.DateTime> purchasedDate { get; set; }
        public Nullable<decimal> pricePaid { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
