//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp2084_a2_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int Id { get; set; }
        public string authorId { get; set; }
        public string title { get; set; }
        public string notes { get; set; }
        public Nullable<int> assetId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string assetCallSign { get; set; }
    }
}
